# docker-compose.yml

services:

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - HOST=${HOST}
      - PORT=${PORT}
    command: uvicorn app.main:app --host ${HOST} --port ${PORT}

  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "9000:9000"
    volumes:
      - .:/docs
    working_dir: /docs
    command: serve -a 0.0.0.0:9000

volumes:
    pgdata:
