site_name: FastAPI Todo App
site_description: Documentation for the FastAPI Todo application
site_author: Your Name

nav:
  - Home: index.md
  - API Reference: api.md
  - Project Structure: project-structure.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables

plugins:
  - search
